/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aug3.test.io.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ServiceInstance extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ServiceInstance\",\"namespace\":\"com.aug3.test.io.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"uri\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"UriSpec\",\"fields\":[{\"name\":\"host\",\"type\":\"string\"},{\"name\":\"port\",\"type\":\"int\"},{\"name\":\"scheme\",\"type\":{\"type\":\"enum\",\"name\":\"ProtocolType\",\"symbols\":[\"HTTP\",\"RPC\",\"AMQP\"]}}]}}},{\"name\":\"ts\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public int id;
  @Deprecated public java.util.List<com.aug3.test.io.avro.UriSpec> uri;
  @Deprecated public long ts;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ServiceInstance() {}

  /**
   * All-args constructor.
   */
  public ServiceInstance(java.lang.CharSequence name, java.lang.Integer id, java.util.List<com.aug3.test.io.avro.UriSpec> uri, java.lang.Long ts) {
    this.name = name;
    this.id = id;
    this.uri = uri;
    this.ts = ts;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return id;
    case 2: return uri;
    case 3: return ts;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: id = (java.lang.Integer)value$; break;
    case 2: uri = (java.util.List<com.aug3.test.io.avro.UriSpec>)value$; break;
    case 3: ts = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'uri' field.
   */
  public java.util.List<com.aug3.test.io.avro.UriSpec> getUri() {
    return uri;
  }

  /**
   * Sets the value of the 'uri' field.
   * @param value the value to set.
   */
  public void setUri(java.util.List<com.aug3.test.io.avro.UriSpec> value) {
    this.uri = value;
  }

  /**
   * Gets the value of the 'ts' field.
   */
  public java.lang.Long getTs() {
    return ts;
  }

  /**
   * Sets the value of the 'ts' field.
   * @param value the value to set.
   */
  public void setTs(java.lang.Long value) {
    this.ts = value;
  }

  /** Creates a new ServiceInstance RecordBuilder */
  public static com.aug3.test.io.avro.ServiceInstance.Builder newBuilder() {
    return new com.aug3.test.io.avro.ServiceInstance.Builder();
  }
  
  /** Creates a new ServiceInstance RecordBuilder by copying an existing Builder */
  public static com.aug3.test.io.avro.ServiceInstance.Builder newBuilder(com.aug3.test.io.avro.ServiceInstance.Builder other) {
    return new com.aug3.test.io.avro.ServiceInstance.Builder(other);
  }
  
  /** Creates a new ServiceInstance RecordBuilder by copying an existing ServiceInstance instance */
  public static com.aug3.test.io.avro.ServiceInstance.Builder newBuilder(com.aug3.test.io.avro.ServiceInstance other) {
    return new com.aug3.test.io.avro.ServiceInstance.Builder(other);
  }
  
  /**
   * RecordBuilder for ServiceInstance instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ServiceInstance>
    implements org.apache.avro.data.RecordBuilder<ServiceInstance> {

    private java.lang.CharSequence name;
    private int id;
    private java.util.List<com.aug3.test.io.avro.UriSpec> uri;
    private long ts;

    /** Creates a new Builder */
    private Builder() {
      super(com.aug3.test.io.avro.ServiceInstance.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.aug3.test.io.avro.ServiceInstance.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.uri)) {
        this.uri = data().deepCopy(fields()[2].schema(), other.uri);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ts)) {
        this.ts = data().deepCopy(fields()[3].schema(), other.ts);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ServiceInstance instance */
    private Builder(com.aug3.test.io.avro.ServiceInstance other) {
            super(com.aug3.test.io.avro.ServiceInstance.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.uri)) {
        this.uri = data().deepCopy(fields()[2].schema(), other.uri);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ts)) {
        this.ts = data().deepCopy(fields()[3].schema(), other.ts);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.aug3.test.io.avro.ServiceInstance.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public com.aug3.test.io.avro.ServiceInstance.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public com.aug3.test.io.avro.ServiceInstance.Builder setId(int value) {
      validate(fields()[1], value);
      this.id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'id' field */
    public com.aug3.test.io.avro.ServiceInstance.Builder clearId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'uri' field */
    public java.util.List<com.aug3.test.io.avro.UriSpec> getUri() {
      return uri;
    }
    
    /** Sets the value of the 'uri' field */
    public com.aug3.test.io.avro.ServiceInstance.Builder setUri(java.util.List<com.aug3.test.io.avro.UriSpec> value) {
      validate(fields()[2], value);
      this.uri = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'uri' field has been set */
    public boolean hasUri() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'uri' field */
    public com.aug3.test.io.avro.ServiceInstance.Builder clearUri() {
      uri = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'ts' field */
    public java.lang.Long getTs() {
      return ts;
    }
    
    /** Sets the value of the 'ts' field */
    public com.aug3.test.io.avro.ServiceInstance.Builder setTs(long value) {
      validate(fields()[3], value);
      this.ts = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'ts' field has been set */
    public boolean hasTs() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'ts' field */
    public com.aug3.test.io.avro.ServiceInstance.Builder clearTs() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public ServiceInstance build() {
      try {
        ServiceInstance record = new ServiceInstance();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.id = fieldSetFlags()[1] ? this.id : (java.lang.Integer) defaultValue(fields()[1]);
        record.uri = fieldSetFlags()[2] ? this.uri : (java.util.List<com.aug3.test.io.avro.UriSpec>) defaultValue(fields()[2]);
        record.ts = fieldSetFlags()[3] ? this.ts : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
