// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: servicePool.proto

package com.aug3.test.io.pb;

public final class ServicePoolProtos {
  private ServicePoolProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServiceInstanceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.ServiceInstance)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
     */
    java.util.List<com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec> 
        getUriList();
    /**
     * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
     */
    com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec getUri(int index);
    /**
     * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
     */
    int getUriCount();
    /**
     * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
     */
    java.util.List<? extends com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpecOrBuilder> 
        getUriOrBuilderList();
    /**
     * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
     */
    com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpecOrBuilder getUriOrBuilder(
        int index);

    /**
     * <code>optional int64 ts = 4;</code>
     */
    boolean hasTs();
    /**
     * <code>optional int64 ts = 4;</code>
     */
    long getTs();
  }
  /**
   * Protobuf type {@code pb.ServiceInstance}
   */
  public static final class ServiceInstance extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pb.ServiceInstance)
      ServiceInstanceOrBuilder {
    // Use ServiceInstance.newBuilder() to construct.
    private ServiceInstance(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServiceInstance(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServiceInstance defaultInstance;
    public static ServiceInstance getDefaultInstance() {
      return defaultInstance;
    }

    public ServiceInstance getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceInstance(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                uri_ = new java.util.ArrayList<com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec>();
                mutable_bitField0_ |= 0x00000004;
              }
              uri_.add(input.readMessage(com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              ts_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          uri_ = java.util.Collections.unmodifiableList(uri_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aug3.test.io.pb.ServicePoolProtos.internal_static_pb_ServiceInstance_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aug3.test.io.pb.ServicePoolProtos.internal_static_pb_ServiceInstance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.class, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.Builder.class);
    }

    public static com.google.protobuf.Parser<ServiceInstance> PARSER =
        new com.google.protobuf.AbstractParser<ServiceInstance>() {
      public ServiceInstance parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServiceInstance(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceInstance> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code pb.ServiceInstance.ProtocolType}
     */
    public enum ProtocolType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HTTP = 0;</code>
       */
      HTTP(0, 0),
      /**
       * <code>RPC = 1;</code>
       */
      RPC(1, 1),
      /**
       * <code>AMQP = 2;</code>
       */
      AMQP(2, 2),
      ;

      /**
       * <code>HTTP = 0;</code>
       */
      public static final int HTTP_VALUE = 0;
      /**
       * <code>RPC = 1;</code>
       */
      public static final int RPC_VALUE = 1;
      /**
       * <code>AMQP = 2;</code>
       */
      public static final int AMQP_VALUE = 2;


      public final int getNumber() { return value; }

      public static ProtocolType valueOf(int value) {
        switch (value) {
          case 0: return HTTP;
          case 1: return RPC;
          case 2: return AMQP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ProtocolType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ProtocolType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ProtocolType>() {
              public ProtocolType findValueByNumber(int number) {
                return ProtocolType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.getDescriptor().getEnumTypes().get(0);
      }

      private static final ProtocolType[] VALUES = values();

      public static ProtocolType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ProtocolType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pb.ServiceInstance.ProtocolType)
    }

    public interface UriSpecOrBuilder extends
        // @@protoc_insertion_point(interface_extends:pb.ServiceInstance.UriSpec)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string host = 1;</code>
       */
      boolean hasHost();
      /**
       * <code>required string host = 1;</code>
       */
      java.lang.String getHost();
      /**
       * <code>required string host = 1;</code>
       */
      com.google.protobuf.ByteString
          getHostBytes();

      /**
       * <code>required int32 port = 2;</code>
       */
      boolean hasPort();
      /**
       * <code>required int32 port = 2;</code>
       */
      int getPort();

      /**
       * <code>optional .pb.ServiceInstance.ProtocolType type = 3 [default = HTTP];</code>
       */
      boolean hasType();
      /**
       * <code>optional .pb.ServiceInstance.ProtocolType type = 3 [default = HTTP];</code>
       */
      com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.ProtocolType getType();
    }
    /**
     * Protobuf type {@code pb.ServiceInstance.UriSpec}
     */
    public static final class UriSpec extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:pb.ServiceInstance.UriSpec)
        UriSpecOrBuilder {
      // Use UriSpec.newBuilder() to construct.
      private UriSpec(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private UriSpec(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final UriSpec defaultInstance;
      public static UriSpec getDefaultInstance() {
        return defaultInstance;
      }

      public UriSpec getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private UriSpec(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                host_ = bs;
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                port_ = input.readInt32();
                break;
              }
              case 24: {
                int rawValue = input.readEnum();
                com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.ProtocolType value = com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.ProtocolType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(3, rawValue);
                } else {
                  bitField0_ |= 0x00000004;
                  type_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aug3.test.io.pb.ServicePoolProtos.internal_static_pb_ServiceInstance_UriSpec_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aug3.test.io.pb.ServicePoolProtos.internal_static_pb_ServiceInstance_UriSpec_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.class, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.Builder.class);
      }

      public static com.google.protobuf.Parser<UriSpec> PARSER =
          new com.google.protobuf.AbstractParser<UriSpec>() {
        public UriSpec parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new UriSpec(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<UriSpec> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int HOST_FIELD_NUMBER = 1;
      private java.lang.Object host_;
      /**
       * <code>required string host = 1;</code>
       */
      public boolean hasHost() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string host = 1;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            host_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string host = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PORT_FIELD_NUMBER = 2;
      private int port_;
      /**
       * <code>required int32 port = 2;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 port = 2;</code>
       */
      public int getPort() {
        return port_;
      }

      public static final int TYPE_FIELD_NUMBER = 3;
      private com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.ProtocolType type_;
      /**
       * <code>optional .pb.ServiceInstance.ProtocolType type = 3 [default = HTTP];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .pb.ServiceInstance.ProtocolType type = 3 [default = HTTP];</code>
       */
      public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.ProtocolType getType() {
        return type_;
      }

      private void initFields() {
        host_ = "";
        port_ = 0;
        type_ = com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.ProtocolType.HTTP;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasHost()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPort()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getHostBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, port_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeEnum(3, type_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getHostBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, port_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(3, type_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code pb.ServiceInstance.UriSpec}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:pb.ServiceInstance.UriSpec)
          com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpecOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.aug3.test.io.pb.ServicePoolProtos.internal_static_pb_ServiceInstance_UriSpec_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.aug3.test.io.pb.ServicePoolProtos.internal_static_pb_ServiceInstance_UriSpec_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.class, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.Builder.class);
        }

        // Construct using com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          host_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          port_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.ProtocolType.HTTP;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.aug3.test.io.pb.ServicePoolProtos.internal_static_pb_ServiceInstance_UriSpec_descriptor;
        }

        public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec getDefaultInstanceForType() {
          return com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.getDefaultInstance();
        }

        public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec build() {
          com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec buildPartial() {
          com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec result = new com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.host_ = host_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.port_ = port_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec) {
            return mergeFrom((com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec other) {
          if (other == com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.getDefaultInstance()) return this;
          if (other.hasHost()) {
            bitField0_ |= 0x00000001;
            host_ = other.host_;
            onChanged();
          }
          if (other.hasPort()) {
            setPort(other.getPort());
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasHost()) {
            
            return false;
          }
          if (!hasPort()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object host_ = "";
        /**
         * <code>required string host = 1;</code>
         */
        public boolean hasHost() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string host = 1;</code>
         */
        public java.lang.String getHost() {
          java.lang.Object ref = host_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              host_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string host = 1;</code>
         */
        public com.google.protobuf.ByteString
            getHostBytes() {
          java.lang.Object ref = host_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            host_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string host = 1;</code>
         */
        public Builder setHost(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          host_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string host = 1;</code>
         */
        public Builder clearHost() {
          bitField0_ = (bitField0_ & ~0x00000001);
          host_ = getDefaultInstance().getHost();
          onChanged();
          return this;
        }
        /**
         * <code>required string host = 1;</code>
         */
        public Builder setHostBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          host_ = value;
          onChanged();
          return this;
        }

        private int port_ ;
        /**
         * <code>required int32 port = 2;</code>
         */
        public boolean hasPort() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 port = 2;</code>
         */
        public int getPort() {
          return port_;
        }
        /**
         * <code>required int32 port = 2;</code>
         */
        public Builder setPort(int value) {
          bitField0_ |= 0x00000002;
          port_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 port = 2;</code>
         */
        public Builder clearPort() {
          bitField0_ = (bitField0_ & ~0x00000002);
          port_ = 0;
          onChanged();
          return this;
        }

        private com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.ProtocolType type_ = com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.ProtocolType.HTTP;
        /**
         * <code>optional .pb.ServiceInstance.ProtocolType type = 3 [default = HTTP];</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional .pb.ServiceInstance.ProtocolType type = 3 [default = HTTP];</code>
         */
        public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.ProtocolType getType() {
          return type_;
        }
        /**
         * <code>optional .pb.ServiceInstance.ProtocolType type = 3 [default = HTTP];</code>
         */
        public Builder setType(com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.ProtocolType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000004;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .pb.ServiceInstance.ProtocolType type = 3 [default = HTTP];</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000004);
          type_ = com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.ProtocolType.HTTP;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:pb.ServiceInstance.UriSpec)
      }

      static {
        defaultInstance = new UriSpec(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:pb.ServiceInstance.UriSpec)
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int URI_FIELD_NUMBER = 3;
    private java.util.List<com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec> uri_;
    /**
     * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
     */
    public java.util.List<com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec> getUriList() {
      return uri_;
    }
    /**
     * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
     */
    public java.util.List<? extends com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpecOrBuilder> 
        getUriOrBuilderList() {
      return uri_;
    }
    /**
     * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
     */
    public int getUriCount() {
      return uri_.size();
    }
    /**
     * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
     */
    public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec getUri(int index) {
      return uri_.get(index);
    }
    /**
     * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
     */
    public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpecOrBuilder getUriOrBuilder(
        int index) {
      return uri_.get(index);
    }

    public static final int TS_FIELD_NUMBER = 4;
    private long ts_;
    /**
     * <code>optional int64 ts = 4;</code>
     */
    public boolean hasTs() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 ts = 4;</code>
     */
    public long getTs() {
      return ts_;
    }

    private void initFields() {
      name_ = "";
      id_ = 0;
      uri_ = java.util.Collections.emptyList();
      ts_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getUriCount(); i++) {
        if (!getUri(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      for (int i = 0; i < uri_.size(); i++) {
        output.writeMessage(3, uri_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(4, ts_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      for (int i = 0; i < uri_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, uri_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, ts_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.ServiceInstance}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.ServiceInstance)
        com.aug3.test.io.pb.ServicePoolProtos.ServiceInstanceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aug3.test.io.pb.ServicePoolProtos.internal_static_pb_ServiceInstance_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aug3.test.io.pb.ServicePoolProtos.internal_static_pb_ServiceInstance_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.class, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.Builder.class);
      }

      // Construct using com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUriFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (uriBuilder_ == null) {
          uri_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          uriBuilder_.clear();
        }
        ts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aug3.test.io.pb.ServicePoolProtos.internal_static_pb_ServiceInstance_descriptor;
      }

      public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance getDefaultInstanceForType() {
        return com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.getDefaultInstance();
      }

      public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance build() {
        com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance buildPartial() {
        com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance result = new com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (uriBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            uri_ = java.util.Collections.unmodifiableList(uri_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.uri_ = uri_;
        } else {
          result.uri_ = uriBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ts_ = ts_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance) {
          return mergeFrom((com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance other) {
        if (other == com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (uriBuilder_ == null) {
          if (!other.uri_.isEmpty()) {
            if (uri_.isEmpty()) {
              uri_ = other.uri_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureUriIsMutable();
              uri_.addAll(other.uri_);
            }
            onChanged();
          }
        } else {
          if (!other.uri_.isEmpty()) {
            if (uriBuilder_.isEmpty()) {
              uriBuilder_.dispose();
              uriBuilder_ = null;
              uri_ = other.uri_;
              bitField0_ = (bitField0_ & ~0x00000004);
              uriBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUriFieldBuilder() : null;
            } else {
              uriBuilder_.addAllMessages(other.uri_);
            }
          }
        }
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getUriCount(); i++) {
          if (!getUri(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec> uri_ =
        java.util.Collections.emptyList();
      private void ensureUriIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          uri_ = new java.util.ArrayList<com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec>(uri_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.Builder, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpecOrBuilder> uriBuilder_;

      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public java.util.List<com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec> getUriList() {
        if (uriBuilder_ == null) {
          return java.util.Collections.unmodifiableList(uri_);
        } else {
          return uriBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public int getUriCount() {
        if (uriBuilder_ == null) {
          return uri_.size();
        } else {
          return uriBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec getUri(int index) {
        if (uriBuilder_ == null) {
          return uri_.get(index);
        } else {
          return uriBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public Builder setUri(
          int index, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec value) {
        if (uriBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUriIsMutable();
          uri_.set(index, value);
          onChanged();
        } else {
          uriBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public Builder setUri(
          int index, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.Builder builderForValue) {
        if (uriBuilder_ == null) {
          ensureUriIsMutable();
          uri_.set(index, builderForValue.build());
          onChanged();
        } else {
          uriBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public Builder addUri(com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec value) {
        if (uriBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUriIsMutable();
          uri_.add(value);
          onChanged();
        } else {
          uriBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public Builder addUri(
          int index, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec value) {
        if (uriBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUriIsMutable();
          uri_.add(index, value);
          onChanged();
        } else {
          uriBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public Builder addUri(
          com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.Builder builderForValue) {
        if (uriBuilder_ == null) {
          ensureUriIsMutable();
          uri_.add(builderForValue.build());
          onChanged();
        } else {
          uriBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public Builder addUri(
          int index, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.Builder builderForValue) {
        if (uriBuilder_ == null) {
          ensureUriIsMutable();
          uri_.add(index, builderForValue.build());
          onChanged();
        } else {
          uriBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public Builder addAllUri(
          java.lang.Iterable<? extends com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec> values) {
        if (uriBuilder_ == null) {
          ensureUriIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, uri_);
          onChanged();
        } else {
          uriBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public Builder clearUri() {
        if (uriBuilder_ == null) {
          uri_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          uriBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public Builder removeUri(int index) {
        if (uriBuilder_ == null) {
          ensureUriIsMutable();
          uri_.remove(index);
          onChanged();
        } else {
          uriBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.Builder getUriBuilder(
          int index) {
        return getUriFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpecOrBuilder getUriOrBuilder(
          int index) {
        if (uriBuilder_ == null) {
          return uri_.get(index);  } else {
          return uriBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public java.util.List<? extends com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpecOrBuilder> 
           getUriOrBuilderList() {
        if (uriBuilder_ != null) {
          return uriBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(uri_);
        }
      }
      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.Builder addUriBuilder() {
        return getUriFieldBuilder().addBuilder(
            com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.getDefaultInstance());
      }
      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.Builder addUriBuilder(
          int index) {
        return getUriFieldBuilder().addBuilder(
            index, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.getDefaultInstance());
      }
      /**
       * <code>repeated .pb.ServiceInstance.UriSpec uri = 3;</code>
       */
      public java.util.List<com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.Builder> 
           getUriBuilderList() {
        return getUriFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.Builder, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpecOrBuilder> 
          getUriFieldBuilder() {
        if (uriBuilder_ == null) {
          uriBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpec.Builder, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.UriSpecOrBuilder>(
                  uri_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          uri_ = null;
        }
        return uriBuilder_;
      }

      private long ts_ ;
      /**
       * <code>optional int64 ts = 4;</code>
       */
      public boolean hasTs() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 ts = 4;</code>
       */
      public long getTs() {
        return ts_;
      }
      /**
       * <code>optional int64 ts = 4;</code>
       */
      public Builder setTs(long value) {
        bitField0_ |= 0x00000008;
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 ts = 4;</code>
       */
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ts_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pb.ServiceInstance)
    }

    static {
      defaultInstance = new ServiceInstance(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pb.ServiceInstance)
  }

  public interface ServicePoolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.ServicePool)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .pb.ServiceInstance si = 1;</code>
     */
    java.util.List<com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance> 
        getSiList();
    /**
     * <code>repeated .pb.ServiceInstance si = 1;</code>
     */
    com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance getSi(int index);
    /**
     * <code>repeated .pb.ServiceInstance si = 1;</code>
     */
    int getSiCount();
    /**
     * <code>repeated .pb.ServiceInstance si = 1;</code>
     */
    java.util.List<? extends com.aug3.test.io.pb.ServicePoolProtos.ServiceInstanceOrBuilder> 
        getSiOrBuilderList();
    /**
     * <code>repeated .pb.ServiceInstance si = 1;</code>
     */
    com.aug3.test.io.pb.ServicePoolProtos.ServiceInstanceOrBuilder getSiOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pb.ServicePool}
   */
  public static final class ServicePool extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pb.ServicePool)
      ServicePoolOrBuilder {
    // Use ServicePool.newBuilder() to construct.
    private ServicePool(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServicePool(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServicePool defaultInstance;
    public static ServicePool getDefaultInstance() {
      return defaultInstance;
    }

    public ServicePool getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServicePool(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                si_ = new java.util.ArrayList<com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance>();
                mutable_bitField0_ |= 0x00000001;
              }
              si_.add(input.readMessage(com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          si_ = java.util.Collections.unmodifiableList(si_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aug3.test.io.pb.ServicePoolProtos.internal_static_pb_ServicePool_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aug3.test.io.pb.ServicePoolProtos.internal_static_pb_ServicePool_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aug3.test.io.pb.ServicePoolProtos.ServicePool.class, com.aug3.test.io.pb.ServicePoolProtos.ServicePool.Builder.class);
    }

    public static com.google.protobuf.Parser<ServicePool> PARSER =
        new com.google.protobuf.AbstractParser<ServicePool>() {
      public ServicePool parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServicePool(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServicePool> getParserForType() {
      return PARSER;
    }

    public static final int SI_FIELD_NUMBER = 1;
    private java.util.List<com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance> si_;
    /**
     * <code>repeated .pb.ServiceInstance si = 1;</code>
     */
    public java.util.List<com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance> getSiList() {
      return si_;
    }
    /**
     * <code>repeated .pb.ServiceInstance si = 1;</code>
     */
    public java.util.List<? extends com.aug3.test.io.pb.ServicePoolProtos.ServiceInstanceOrBuilder> 
        getSiOrBuilderList() {
      return si_;
    }
    /**
     * <code>repeated .pb.ServiceInstance si = 1;</code>
     */
    public int getSiCount() {
      return si_.size();
    }
    /**
     * <code>repeated .pb.ServiceInstance si = 1;</code>
     */
    public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance getSi(int index) {
      return si_.get(index);
    }
    /**
     * <code>repeated .pb.ServiceInstance si = 1;</code>
     */
    public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstanceOrBuilder getSiOrBuilder(
        int index) {
      return si_.get(index);
    }

    private void initFields() {
      si_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getSiCount(); i++) {
        if (!getSi(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < si_.size(); i++) {
        output.writeMessage(1, si_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < si_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, si_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.aug3.test.io.pb.ServicePoolProtos.ServicePool parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServicePool parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServicePool parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServicePool parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServicePool parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServicePool parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServicePool parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServicePool parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServicePool parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.aug3.test.io.pb.ServicePoolProtos.ServicePool parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aug3.test.io.pb.ServicePoolProtos.ServicePool prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.ServicePool}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.ServicePool)
        com.aug3.test.io.pb.ServicePoolProtos.ServicePoolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aug3.test.io.pb.ServicePoolProtos.internal_static_pb_ServicePool_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aug3.test.io.pb.ServicePoolProtos.internal_static_pb_ServicePool_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aug3.test.io.pb.ServicePoolProtos.ServicePool.class, com.aug3.test.io.pb.ServicePoolProtos.ServicePool.Builder.class);
      }

      // Construct using com.aug3.test.io.pb.ServicePoolProtos.ServicePool.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSiFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (siBuilder_ == null) {
          si_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          siBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aug3.test.io.pb.ServicePoolProtos.internal_static_pb_ServicePool_descriptor;
      }

      public com.aug3.test.io.pb.ServicePoolProtos.ServicePool getDefaultInstanceForType() {
        return com.aug3.test.io.pb.ServicePoolProtos.ServicePool.getDefaultInstance();
      }

      public com.aug3.test.io.pb.ServicePoolProtos.ServicePool build() {
        com.aug3.test.io.pb.ServicePoolProtos.ServicePool result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aug3.test.io.pb.ServicePoolProtos.ServicePool buildPartial() {
        com.aug3.test.io.pb.ServicePoolProtos.ServicePool result = new com.aug3.test.io.pb.ServicePoolProtos.ServicePool(this);
        int from_bitField0_ = bitField0_;
        if (siBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            si_ = java.util.Collections.unmodifiableList(si_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.si_ = si_;
        } else {
          result.si_ = siBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aug3.test.io.pb.ServicePoolProtos.ServicePool) {
          return mergeFrom((com.aug3.test.io.pb.ServicePoolProtos.ServicePool)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aug3.test.io.pb.ServicePoolProtos.ServicePool other) {
        if (other == com.aug3.test.io.pb.ServicePoolProtos.ServicePool.getDefaultInstance()) return this;
        if (siBuilder_ == null) {
          if (!other.si_.isEmpty()) {
            if (si_.isEmpty()) {
              si_ = other.si_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSiIsMutable();
              si_.addAll(other.si_);
            }
            onChanged();
          }
        } else {
          if (!other.si_.isEmpty()) {
            if (siBuilder_.isEmpty()) {
              siBuilder_.dispose();
              siBuilder_ = null;
              si_ = other.si_;
              bitField0_ = (bitField0_ & ~0x00000001);
              siBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSiFieldBuilder() : null;
            } else {
              siBuilder_.addAllMessages(other.si_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSiCount(); i++) {
          if (!getSi(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aug3.test.io.pb.ServicePoolProtos.ServicePool parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aug3.test.io.pb.ServicePoolProtos.ServicePool) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance> si_ =
        java.util.Collections.emptyList();
      private void ensureSiIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          si_ = new java.util.ArrayList<com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance>(si_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.Builder, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstanceOrBuilder> siBuilder_;

      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public java.util.List<com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance> getSiList() {
        if (siBuilder_ == null) {
          return java.util.Collections.unmodifiableList(si_);
        } else {
          return siBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public int getSiCount() {
        if (siBuilder_ == null) {
          return si_.size();
        } else {
          return siBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance getSi(int index) {
        if (siBuilder_ == null) {
          return si_.get(index);
        } else {
          return siBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public Builder setSi(
          int index, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance value) {
        if (siBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSiIsMutable();
          si_.set(index, value);
          onChanged();
        } else {
          siBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public Builder setSi(
          int index, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.Builder builderForValue) {
        if (siBuilder_ == null) {
          ensureSiIsMutable();
          si_.set(index, builderForValue.build());
          onChanged();
        } else {
          siBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public Builder addSi(com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance value) {
        if (siBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSiIsMutable();
          si_.add(value);
          onChanged();
        } else {
          siBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public Builder addSi(
          int index, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance value) {
        if (siBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSiIsMutable();
          si_.add(index, value);
          onChanged();
        } else {
          siBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public Builder addSi(
          com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.Builder builderForValue) {
        if (siBuilder_ == null) {
          ensureSiIsMutable();
          si_.add(builderForValue.build());
          onChanged();
        } else {
          siBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public Builder addSi(
          int index, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.Builder builderForValue) {
        if (siBuilder_ == null) {
          ensureSiIsMutable();
          si_.add(index, builderForValue.build());
          onChanged();
        } else {
          siBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public Builder addAllSi(
          java.lang.Iterable<? extends com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance> values) {
        if (siBuilder_ == null) {
          ensureSiIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, si_);
          onChanged();
        } else {
          siBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public Builder clearSi() {
        if (siBuilder_ == null) {
          si_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          siBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public Builder removeSi(int index) {
        if (siBuilder_ == null) {
          ensureSiIsMutable();
          si_.remove(index);
          onChanged();
        } else {
          siBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.Builder getSiBuilder(
          int index) {
        return getSiFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstanceOrBuilder getSiOrBuilder(
          int index) {
        if (siBuilder_ == null) {
          return si_.get(index);  } else {
          return siBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public java.util.List<? extends com.aug3.test.io.pb.ServicePoolProtos.ServiceInstanceOrBuilder> 
           getSiOrBuilderList() {
        if (siBuilder_ != null) {
          return siBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(si_);
        }
      }
      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.Builder addSiBuilder() {
        return getSiFieldBuilder().addBuilder(
            com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.getDefaultInstance());
      }
      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.Builder addSiBuilder(
          int index) {
        return getSiFieldBuilder().addBuilder(
            index, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.getDefaultInstance());
      }
      /**
       * <code>repeated .pb.ServiceInstance si = 1;</code>
       */
      public java.util.List<com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.Builder> 
           getSiBuilderList() {
        return getSiFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.Builder, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstanceOrBuilder> 
          getSiFieldBuilder() {
        if (siBuilder_ == null) {
          siBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstance.Builder, com.aug3.test.io.pb.ServicePoolProtos.ServiceInstanceOrBuilder>(
                  si_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          si_ = null;
        }
        return siBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:pb.ServicePool)
    }

    static {
      defaultInstance = new ServicePool(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pb.ServicePool)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ServiceInstance_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_ServiceInstance_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ServiceInstance_UriSpec_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_ServiceInstance_UriSpec_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ServicePool_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_ServicePool_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021servicePool.proto\022\002pb\"\353\001\n\017ServiceInsta" +
      "nce\022\014\n\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022(\n\003uri\030\003 \003" +
      "(\0132\033.pb.ServiceInstance.UriSpec\022\n\n\002ts\030\004 " +
      "\001(\003\032[\n\007UriSpec\022\014\n\004host\030\001 \002(\t\022\014\n\004port\030\002 \002" +
      "(\005\0224\n\004type\030\003 \001(\0162 .pb.ServiceInstance.Pr" +
      "otocolType:\004HTTP\"+\n\014ProtocolType\022\010\n\004HTTP" +
      "\020\000\022\007\n\003RPC\020\001\022\010\n\004AMQP\020\002\".\n\013ServicePool\022\037\n\002" +
      "si\030\001 \003(\0132\023.pb.ServiceInstanceB(\n\023com.aug" +
      "3.test.io.pbB\021ServicePoolProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pb_ServiceInstance_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_ServiceInstance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pb_ServiceInstance_descriptor,
        new java.lang.String[] { "Name", "Id", "Uri", "Ts", });
    internal_static_pb_ServiceInstance_UriSpec_descriptor =
      internal_static_pb_ServiceInstance_descriptor.getNestedTypes().get(0);
    internal_static_pb_ServiceInstance_UriSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pb_ServiceInstance_UriSpec_descriptor,
        new java.lang.String[] { "Host", "Port", "Type", });
    internal_static_pb_ServicePool_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_ServicePool_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pb_ServicePool_descriptor,
        new java.lang.String[] { "Si", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
